# Generated by Django 4.0.6 on 2022-07-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_carditem_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='car_id',
            new_name='cart_id',
        ),
    ]
